# import = [
#   "~/.config/alacritty/catppuccin-mocha.toml"
# ]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.9  # Adjust this value to control transparency (0.0 to 1.0)

[cursor]
style = "Beam"

[colors.primary]
background = "#000000"  # Black background

