"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$time\
$line_break$character""" 
palette = 'catppuccin_mocha'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "fg:text"

[os.symbols]
Arch = " "

[username]
show_always = false
style_user = "fg:text"
style_root = "fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:pink"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:green"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:green"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
style = "fg:teal"
format = '[ $symbol( $version) ]($style)'

[c]
symbol = " "
style = "fg:teal"
format = '[ $symbol( $version) ]($style)'

[rust]
symbol = ""
style = "fg:teal"
format = '[ $symbol( $version) ]($style)'

[golang]
symbol = ""
style = "fg:teal"
format = '[ $symbol( $version) ]($style)'

[php]
symbol = ""
style = "fg:teal"
format = '[ $symbol( $version) ]($style)'

[java]
symbol = " "
style = "fg:teal"
format = '[ $symbol( $version) ]($style)'

[kotlin]
symbol = ""
style = "fg:teal"
format = '[ $symbol( $version) ]($style)'

[haskell]
symbol = ""
style = "fg:teal"
format = '[ $symbol( $version) ]($style)'

[python]
symbol = ""
style = "fg:teal"
format = '[ $symbol( $version) ]($style)'

[docker_context]
symbol = ""
style = "fg:#83a598"
format = '[ $symbol( $context) ]($style)'

[time]
disabled = true
time_format = "%R"
style = "fg:purple"
# format = '[  $time ]($style)'
format = '[ $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
