keybinding:
  universal:
    prevItem-alt: l
    nextItem-alt: k
    prevBlock-alt: j
    nextBlock-alt: ;
    scrollUpMain-alt1: L
    scrollDownMain-alt1: k
  commits:
    moveDownCommit: <c-k>
    moveUpCommit: <c-l>
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --config ~/.config/delta/.gitconfig --hunk-header-decoration-style ""
quitOnTopLevelReturn: true
showCommandLog: false
