keybinding:
  universal:
    prevItem-alt: l
    nextItem-alt: k
    prevBlock-alt: j
    nextBlock-alt: ;
    scrollUpMain-alt1: L
    scrollDownMain-alt1: k
  commits:
    moveDownCommit: <c-k>
    moveUpCommit: <c-l>
git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers
  commits:
    moveDownCommit: <c-k>
    moveUpCommit: <c-l>


quitOnTopLevelReturn: true
showCommandLog: false
