[accounts.gmail]
default=true
email = "noetrevino.music@gmail.com"

folder.aliases.inbox = "INBOX"
folder.aliases.sent = "[Gmail]/Sent Mail"
folder.aliases.drafts = "[Gmail]/Drafts"
folder.aliases.trash = "[Gmail]/Trash"

backend.type = "imap"
backend.host = "imap.gmail.com"
backend.port = 993
backend.login = "noetrevino.music@gmail.com"
backend.auth.type = "password"
backend.auth.raw = "ayqimnwebdchebuy"

message.send.backend.type = "smtp"
message.send.backend.host = "smtp.gmail.com"
message.send.backend.port = 465
message.send.backend.login = "noetrevino.music@gmail.com"
message.send.backend.auth.type = "password"
message.send.backend.auth.raw = "ayqimnwebdchebuy"
