preload = ~/.config/wallpapers/knahut.jpg
preload = ~/.config/wallpapers/anime-motorcycle.png
preload = ~/.config/wallpapers/hny.jpg
preload = ~/.config/wallpapers/blue-girl.jpg

wallpaper = DP-2, ~/.config/wallpapers/knahut.jpg
wallpaper = DP-3, ~/.config/wallpapers/blue-girl.jpg
wallpaper = HDMI-A-1, ~/.config/wallpapers/hny.jpg
