preload = ~/.config/wallpapers/knahut.jpg
preload = ~/.config/wallpapers/anime-motorcycle.png
preload = ~/.config/wallpapers/hny.jpg
preload = ~/.config/wallpapers/blue-girl.jpg
preload = ~/.config/wallpapers/blue-girl.jpg
preload = ~/Downloads/arch-linux.png

wallpaper = eDP-1, ~/Downloads/arch-linux.png
